import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";




export const metadata: Metadata = {
  title: "Home",
  description: "Generated by Hayas World",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className="font-title "
        
      >
       {children}
       <Toaster />
      </body>
    </html>
  );
}
